### ISSUE TITLE
Umbrella issue: mTLS with cert-manager 

### ISSUE THREAD

**Issue by alexandrevilain** [alexandrevilain/temporal-operator#746]
Temporal operator v0.19.0 will released in the coming hours/days.

It looks like mTLS with cert-manager is having some issues that I would like to fix for v0.20.0 release (at least before 1.0.0 and before v1 API, in case of breaking API changes required).

Here is a list of open or closed issues that can help us find what's going wrong:
- https://github.com/alexandrevilain/temporal-operator/issues/722
- https://github.com/alexandrevilain/temporal-operator/issues/708
- https://github.com/alexandrevilain/temporal-operator/issues/472
- https://github.com/alexandrevilain/temporal-operator/issues/501
- https://github.com/alexandrevilain/temporal-operator/issues/509

IMO the work should be done in the following step:
- [ ] Fixing the client certificates issues
- [ ] Fixing the certificate rotation issues
- [ ] Improving the UI/UX of the feature

As a reminder here is the current certificate architecure diagram: https://temporal-operator.pages.dev/features/mtls/cert-manager/

Things to consider:
- https://github.com/cert-manager/csi-driver

**Comment by yujunz** [comment]
cc @guritinvda

**Comment by ElanHasson** [comment]
@alexandrevilain  thank you for addressing this holistically! much appreciated.

**Comment by bmorton** [comment]
I ran into some of these issues too, but I think I have addressed all of them in the various issue threads.  I think if those ideas work in each of those cases, we should be able to get to closure on this whole issue.

**Comment by bmorton** [comment]
I spoke too soon -- #708 is still causing issues for me.  I'll continue investigating around that.
